---

version: '3'
services:
  centos6:
    build:
      context: .
      dockerfile: ./docker/centos6/Dockerfile
    volumes:
      - ./RPMS:/RPMS
  centos7:
    build:
      context: .
      dockerfile: ./docker/centos7/Dockerfile
    volumes:
      - ./RPMS:/RPMS

